version: '3'
services:
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  todo-app:
    depends_on:
      - mysqldb
    image: get-start:v1
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DB=$MYSQLDB_DATABASE
    ports:
      - 3000:3000
volumes: 
  db: