apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-db
spec:
  selector:
    matchLabels:
      app: todo-app-db
  template:
    metadata:
      labels:
        app: todo-app-db
    spec:
      containers:
      - name: todo-app-db
        image: mysql:5.7
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        env:
        - name: MYSQL_USER
          value: 'user'
        - name: MYSQL_DATABASE
          value: 'db'
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        ports:
          - containerPort: 3306
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-db
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: todo-app-db
